name: Feature Request
description: Suggest an idea for improving ToolBelt
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen
    validations:
      required: true
